README.md
[why]
The old instructions still referred to the defunct Stash repo.
[how]
Use the new GitHub HTTPS URL. Also add some minor improvements to the readme.
=> Fix the instructions for cloning the repo

README.md, data/doxygen.h
vcpkg has recently accepted a [portfile for GUL14](https://github.com/microsoft/vcpkg/commit/fd69fb296475fb8c5ef5e3daec57258e5c7ba06d), so the library can now be installed via "vcpkg install gul14". It is probably good to advertise this in a new "installation" section in both the README and the Doxygen documentation.
=> Documentation: Add info on vcpkg installation

data/doxygen.h, include/gul14/date.h, include/gul14/gul.h, include/gul14/meson.build, meson.build, tests/test_backports.cc
This PR adds Howard Hinnant's [date.h](https://github.com/HowardHinnant/date) header as proposed in #7. I have made the "usual" modifications for GUL14: The header is enclosed in namespace `gul14::date::` and it uses `gul14::string_view` instead of `std::string_view`. I also added the necessary pieces of documentation and copyright notices and tentatively increased our version number to 2.7.
=> Add date header

data/doxygen.h, include/gul14/gcd_lcm.h, include/gul14/gul.h, include/gul14/meson.build, tests/meson.build, tests/test_gcd_lcm.cc
These functions can calculate the [greatest common divisor](https://en.wikipedia.org/wiki/Greatest_common_divisor) and [least common multiple](https://en.wikipedia.org/wiki/Least_common_multiple) of two integers.
They are very similar to the C++17 functions [std::gcd()](https://en.cppreference.com/w/cpp/numeric/gcd) and [std::lcm()](https://en.cppreference.com/w/cpp/numeric/lcm), but do not work with integers of different signedness – a static_assert prevents that. This makes them safer to use because the standard versions cause UB when used with one unsigned integer and one negative integer.
=> Add gcd() and lcm()

include/gul14/time_util.h, tests/test_time_util.cc
This MR increases the tolerance for time measurements after `sleep()` in unit tests. It also improves the documentation of several `sleep()` overloads to make it clear that the functions introduce a delay that is *at least* as long as specified.
Many `sleep()` related tests fail on GitHub MacOS runners because the systems are under heavy contention. As `sleep()` is an interruption point, context switches sometimes lead to delays on the order of several tens of milliseconds. We adapt to that by increasing the tolerance after `sleep()` from 18 to 100 ms.
=> Make sleep() time tests more robust

.github/workflows/build-and-run-tests-posix.yml, .github/workflows/ci.yml, .gitignore
This adds a rudimentary GitHub workflow for building GUL14 on Ubuntu. Both a debug build with address sanitizer and a release build are created and their test suites are run.
=> Add rudimentary Github CI configuration

data/doxygen.h, include/gul14/gcd_lcm.h, include/gul14/num_util.h, tests/test_num_util.cc
**[why]**
`gul14::within_orders(0.0, 0.0, 5)` is `false`. Instinctively one might expect it to be true, as both inputs are strictly equal.
**[how]**
Check for equality first, then additionally add some lenience.
Fixes: #17
=> num_util: within_orders() detects 0.0 == 0.0

libgul14.spec
On a standard RHEL7 installation we can not build rpm's unless we have an extra macro installed.
The upstream meson package for RHEL7 [might add this dependency](https://bugzilla.redhat.com/show_bug.cgi?id=2101564), but this may take some time and we may do not wanna wait for it, so we can fix it one our own.
=> rpm: Add workaround for the meson issue

include/gul14/string_view.h
This PR removes `gul14::string_view::to_string()`. C++17's `std::string_view` does not have that member function, so we should not encourage our users to depend on it.
See: [cppreference on std::string_view](https://en.cppreference.com/w/cpp/string/basic_string_view)
=> Remove string_view::to_string()

README.md
Meson 1.0.0 issues a warning if meson is called without a verb argument ("meson builddir" instead of "meson setup builddir"). This PR adds "setup" to the meson invocation examples. It also adds an example with additional cpp_args (as proposed by Sören).
=> Update Meson setup examples

include/gul14/bit_manip.h
This PR fixes two warnings in `bit_manip.h` that appear when compiling with `-Wconversion`.
=> Fix two warnings about implicit casts

include/gul14/num_util.h, tests/test_optional.cc
This PR silences a few more `-Wconversion` warnings.
=> Silence more warnings

include/gul14/statistics.h, tests/test_SmallVector.cc
This PR silences the last batch of warnings. After this commit, GUL14 compiles cleanly with -Wshadow -Wconversion (at least on GCC).
=> Silence a few -Wconversion warnings

include/gul14/to_number.h
This is a bugfix for the missing include of a standard library header as discovered by MSK's Jenkins build. Please review this with priority (but also note that another pull request is still in the queue). :)
[why]
On the openSUSE Tumbleweed Linux distro, compilation of to_number.h fails because of a missing declaration of uint64_t.
[how]
Include cstdint. Also, use the fully namespace-qualified form std::uint64_t as mandated by the standard.
=> Add missing cstdint include

include/gul14/expected.h, include/gul14/meson.build, include/gul14/optional.h, include/gul14/utility.h, tests/test_expected.cc
Unfortunately the last 2.8.0 release is broken. This is the corresponding bugfix. I would retroactively re-tag the fixed version as 2.8.0 unless someone prefers a 2.8.1 release.
[why]
Both optional.h and expected.h provided conflicting declarations of this type/constant. This lead to a compilation error if both headers were included.
[how]
Remove the declarations from optional.h and expected.h and put them into a new utility.h header instead.
=> Move in_place_t and in_place into a new utility.h header

data/doxygen.h, include/gul14/expected.h, include/gul14/gul.h, include/gul14/meson.build, include/gul14/span.h, include/gul14/traits.h, include/gul14/utility.h, include/gul14/variant.h, tests/meson.build, tests/test_variant.cc
This pull request adds a gul14::variant with the same API as C++17's [std::variant](https://en.cppreference.com/w/cpp/utility/variant). The implementation is based on version 1.4.0 of the variant library by Michael Park (https://github.com/mpark/variant). Multiple header files from the original source have been merged into a single file, and multiple conditional compilation blocks have been removed because GUL14 does not support pre-C++14 compilers.
Because of conflicting definitions, I have also extracted a few types and metafunctions so that they can be shared between `variant`, `optional`, `expected`, and `span` (and GUL14 users in general).
I assume this becomes version 2.9.0 when merged.
=> Add a backport of std::variant from C++17

include/gul14/variant.h
As reported by Sören, when compiled with a C++17 compiler, `gul14::variant` causes a compilation error related to `invoke_result_t`. This error does not occur when compiled under C++14.
The bug seems to be subtle. Instead of fixing it directly, we can take advantage of the fact that the various invoke functions and types
```
invoke
invoke_result
invoke_result_t
is_invocable
is_invocable_r
```
are already available in namespace std on a C++17 compiler. Hence, we add a conditional compilation section that simply uses the following declarations on C++17 instead of the home-brew ones:
```cpp
using std::invoke;
using std::invoke_result;
using std::invoke_result_t;
using std::is_invocable;
using std::is_invocable_r;
```
=> Fix compilation errors in gul14::variant when compiled with C++17

include/gul14/variant.h
Apparently some conditionally compiled blocks in `variant.h` were never tested on our usual Linux and Mac platforms. They contain undefined namespace references which blow up the build on Windows.
This PR fixes the bug by correcting some namespace qualifiers to "std::" and adding some library code from Michael Park's original variant implementation.
I'll try to come up with a CI setup for Windows builds on Github next.
Closes #45.
=> Fix compilation errors on Visual Studio

data/doxygen.h
We have fixed a few compilation errors on Windows and when compiled under C++17 and should therefore bump the patch number.
=> Bump version to 2.9.1 and add info on DOOCS release 23.6.0

.github/workflows/testposix.yml, .github/workflows/testwindows.yml
[why]
The test workflows are not triggered on PRs.
[how]
Correct the path filter... forgot the glob.
Also add meson.build to the filter, as changes there might also break builds.
Noticed when reviewing #50
=> CI: Really trigger on PRs

include/gul14/variant.h, tests/test_variant.cc
It seems I underestimated the import of the `variant` header. In fact, `gul14::visit()` could not be used at all (at least for some set of compilers) because of a missing namespace qualifier on one call to `invoke()`. Here's a bugfix.
=> Bugfix for gul14::visit()

debian/meson.build, meson.build, src/meson.build
This will enable more warnings by default. As of right now this will not trigger any new warnings.
=> meson: enable more warnings by default

debian/meson.build, meson.build
When we use libgul as subproject the setup will fail with:
> ERROR: Function 'add_global_arguments' cannot be used in subprojects because there is no way to make that reliable.
Fixes: 114b594a821 (meson: Enable extra warnings by default)
=> meson: Do not use global arguments when subproject

data/doxygen.h, include/gul14/variant.h, tests/test_variant.cc
This PR adds the `OverloadSet` variadic class template and a `make_overload_set()` helper function to create objects of this type. Such a type is recommended for use with `std::visit` by Bjarne Stroustrup in "A Tour of C++" where he writes that "[t]he **overloaded** class is necessary and strangely enough, not standard". Well, at least we should have it. :)
I think we should squeeze this in as patch release 2.9.2. Yes, we enhance the API, but since this is header-only stuff, users can safely ignore it.
Without C++17, we do not have "if constexpr". This can make it hard to
construct a suitable visitor function for gul14::visit(). The
alternative to using "if constexpr" is constructing an overload set of
functions.
Provide a variadic class template OverloadSet that inherits from an …
=> Add OverloadSet and make_overload_set()

data/doxygen.h, include/gul14/bit_manip.h, tests/test_bit_manip.cc
This PR adds an enum class `gul14::endian` that works like C++20's [std::endian](https://en.cppreference.com/w/cpp/types/endian) and two convenience functions `is_little_endian()` and `is_big_endian()`. Together, this offers a simple and portable solution to enquire the system's endianness at compile time.
The PR also separates the documentation for the bit manipulation functions from the numeric functions.
=> Features for determining platform endianness

.github/workflows/testposix.yml, .github/workflows/testwindows.yml
GitHub complains about outdated actions:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, actions/upload-artifact@v3.
We now use the v4 versions of these actions. At the same time, we update Meson from 0.63.0 to 1.3.1.
=> Update GitHub actions and Meson version

.github/workflows/testwindows.yml, include/gul14/string_view.h
**[why]**
Apple clang version 15.0.0 warns:
```
warning: implicit conversion changes signedness:
'size_type' (aka 'unsigned long') to 'difference_type' (aka 'long')
[-Wsign-conversion]
```
**[how]**
_Distances_ can be forward and backward and thus need a signed number.
_Size and index_ is often described by an unsigned number, to double the range and to avoid meaningless negative length.
This has historically been mixed without much thought, although in extreme cases the results were wrong. But usually we do not have strings that long.
To fix this first the private `reverse_distance()` function is removed, because it returns a unsigned number and must return a unsigned number from what it does internally and that does not reflect the concept of 'distance'.
Instead we take the forward …
=> string_view: Fix signed mismatch warning

data/meson.build, debian/control.in, debian/meson.build, meson.build, tests/meson.build, tools/meson.build
**[why]**
Meson 1.3.99 gives these warnings:
```
NOTICE: Future-deprecated features used:
* 0.56.0: {'meson.build_root'}
WARNING: Broken features used:
* 1.3.0: {'str.format: Value other than strings, integers, bools, options, dictionaries and lists thereof.'}
```
**[how]**
We try to get the absolute path of a generated file. Since 1.4.0 we have a `get_path()` member function on the generated file object, but we can not use that on older Mesons.
So instead we just manually assemble the filename in the place where the file is generated and use that later on. Both warned-about functions removed.
Fixes: #64
=> meson: Fix deprecated warning

data/doxygen.h, debian/copyright.in, include/gul14/expected.h, include/gul14/traits.h, include/gul14/variant.h
This PR extracts the definitions of the C++17 backports of
- invoke,
- invoke_result,
- invoke_result_t,
- is_invokable,
- is_invokable_r
from M. Park's variant header and makes them available in the public traits.h header in namespace gul14. The definitions are useful for GUL14 users in general, but we can also use them inside the library. This PR uses them to replace an ad-hoc implementation in our `expected` header, and they will be needed for the `ThreadPool` PR.
=> Provide backports of std::invoke, invoke_result, is_invokable and friends

tests/test_time_util.cc
One of the tests tries to ascertain that sleep(0) or sleep(-5s) does not wait. Strictly speaking, that is impossible to test because the program execution may be interrupted at any time.
Increase the allowed time duration from 1 ms to 100 ms and cross fingers. The only other option I see is to remove the test for good. I'd also be fine with that.
Closes #75
=> time_util: Make time-dependent tests more robust

include/gul14/to_number.h, src/meson.build, src/to_number.cc, tests/test_to_number.cc
**[why]**
For `to_number<long double>()` to work we need a `std::powl()` that is
accurate - its errors directly influence our conversion output, usually
amplified.
In the past we just knew about Apple clang that had a problem with
`std::powl()` being off a bit, but now also Alpine has the same problem
via musl that it uses.
**[how]**
On parsing a string a possible number is expressed with scientific
notification, for example `123.4E5` which means 123.4 * (10^5).
The mantissa is converted to a normalized value as floating point
number, (1.234 in the example) and the exponent is corrected for the
shift of decimal places (5 becomes 7). So the example is transformed
to 1.234 * (10^7).
To calculate the exponent the call `pow(10, 7)` is used. Any inaccuracy
in the calculation directly …
=> Bugfix inaccurate powl

tests/test_to_number.cc
[why]
Ubuntu 16.04 is long time past and not supported anymore.
=> to_number: ~~Activate~~ constexpr tests

tests/test_to_number.cc
**[why]**
On ARM (Raspberry 3 for example):
Small numbers are 2 ULP off of the ideal value but we accept only 1 ULP - albeit we say in the comment we would allow 2 for very small numbers.
These are not yet denormal values.
The problem happens if the highest exponent bit is set (i.e. bit 12 with value 4096) and there are more than 5 multiplications needed.
Fixes: #81
=> to_number: Relax pow10() test

include/gul14/ThreadPool.h, tests/meson.build
**[why]**
Some symbols (functions) are not exported to the shared library. But they are accessed by templated functions, so the call to them is instantiated by user code and the user needs to have access to the functions. That is even then the case when private member functions are involved.
**[how]**
Add export specifier to needed functions. Some few functions seem (!) to have no need for export, so they are excluded from exporting right now.
Maybe we want to export all functions. That whole setup is quite a thicket and it is hard to follow which templated functions call which other templated functions and so in the end need exported basic functions.
Then do the tests again with the shared library.
Another possibility would be to
- Avoid templated functions that call internals (haha)
- …
=> ThreadPool: Fixup: Export missing symbols

include/gul14/ThreadPool.h, tests/test_ThreadPool.cc
Without a default constructor, it is almost impossible to store a `TaskHandle` in some user-defined data structure. This limits its usefulness dramatically. Hence, this PR adds a simple default constructor and a test to check that the default-constructed task handle does what one would expect (namely, nothing useful).
=> ThreadPool::TaskHandle: Add default constructor

include/gul14/SmallVector.h
**[why]**
When the library is compiled with heavy instrumentalization (e.g. gcov) in some cases we get this compiler warning:
```
include/gul14/SmallVector.h:426:13: warning: ‘void operator delete [](void*)’ called on unallocated object ‘v3’ [-Wfree-nonheap-object]
426 |             delete[] data_ptr_;
|             ^~~~~~~~~~~~~~~~~~
```
The problem is the detection if the thing that currently holds the data is allocated or not. At the moment the size (capacity) is used as indirect marker. It seems that this can go wrong.
**[how]**
Use instead the pointed to address directly. We know the address of the internal data-holding array, and when the current data is not THAT is must be allocated.
Fixes: #91
Reviewed-by: Soeren Grunewald <soeren.grunewald@desy.de>
=> SmallVector: Make destructor more robust

data/doxygen.h, include/gul14/to_number.h, tests/test_to_number.cc
**Why**  
The DOOCS Serverlib uses `to_number` when resorting values in `D_array`. But it breaks if we wanna instantiate an array of booleans.
This commit will add basic support to allow `to_number` been used with `bool`.
**How**  
First make sure the other implementations wont trigger, since `bool` is _arithmetic_, _integral_ and _unsigned_. Then add a very simple implementation which allows only `0|1` and `true|false`. And to round things up, add some very basic tests.
=> to_number: Allow basic usage of bool

include/gul14/join_split.h
We documented that the string type must provide an `operator+=(string&, T)`, but forgot that it must also provide a `size()` member. This PR adds that documentation.
=> join(): Document that string type must provide size()

data/meson.build, tools/meson.build
When you do not want to generate the documentation Meson still searches for Doxygen - but it will never be used.
**[why]**  
We search for the `doxygen` executable even if we will never use it because the documentation target is not wanted.
**[how]**  
Put the search for the executable one level deeper.
=> tools: Search for doxygen only if needed

src/escape.cc, src/meson.build, src/replace.cc
[why]
While RVO is guaranteed and we will get warnings about pessimizations the c++17 new optional NRVO is warned on only on request (except on mcvc).
To get optimal code we of course want to benefit from NRVO optimizations.
=> Enable new NRVO warning

data/doxygen.h, include/gul14/ThreadPool.h, meson.build, src/ThreadPool.cc, tests/test_ThreadPool.cc
There are use cases in which it is beneficial to know on which of the *N* pool threads a function gets executed. Sascha recently came up with one such case for the new clientlib NameService.
Store a thread-local thread index when launching the threads. Return this index when called from a worker thread. For other threads, the thread-local index gets initialized to the maximum value of size_t; if this value is found, get_thread_index() throws an exception.
=> ThreadPool: Add get_thread_index()

include/gul14/SmallVector.h
[Why]
The compilation with GCC 15 fails with:
```
In file included from tests/incl_SmallVector.cc:23:
include/gul14/SmallVector.h:277:22: error: ‘uint32_t’ does not name a type [-Wtemplate-body]
277 |     using SizeType = uint32_t;
|                      ^~~~~~~~
include/gul14/SmallVector.h:37:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include  <stdint>’
36 | #include "gul14/cat.h"
+++ |+#include <cstdint>
37 |
```
=> Fix compilation with GCC 15.x.y
